### ISSUE TITLE
Home page with searching

### ISSUE THREAD

**Issue by cshinaver** [cshinaver/BookFinder#28]
- [x] Create home page with search bar (preferably using a template for design's sake)
Searching functionality
- [x] Searching queries database book information 
- [x] Searching starts data scraper and dynamically adds search results to page (will require JS) 
- [ ] Implement caching

**Comment by jhuseman** [comment]
Potential templates:
[cosmo](http://bootswatch.com/cosmo/)
[complex-navbar](http://www.bootstrapzero.com/bootstrap-template/complex-navbar)

**Comment by jhuseman** [comment]
created branch issue_28 to work on this issue.

**Comment by jhuseman** [comment]
Merged in branch issue_28 to implement all except caching. issue_28 is still open to work on caching and cosmetic changes with searching.

**Comment by cshinaver** [comment]
I don't think we need caching for now. We can deal with it later if we find a need for it.
