### ISSUE TITLE
Setup mysql database with wrappings and setup scripts

### ISSUE THREAD

**Issue by cshinaver** [cshinaver/BookFinder#34]
- [x] Set up PostgreSQL database configuration
- [x] Write script for initial schema creation

**Comment by cshinaver** [comment]
Installing MySQL on Linux: https://www.linode.com/docs/databases/mysql/how-to-install-mysql-on-ubuntu-14-04

**Comment by cshinaver** [comment]
Install PostgreSQL on Ubuntu: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-14-04

**Comment by cshinaver** [comment]
You will also need to install `psycopg2` (it was added to the `requirements.txt` file and can be installed using `pip install -r requirements.txt`). On ubuntu, I had to also install the system package `libpq-dev`.

**Comment by cshinaver** [comment]
You also have to set a password for the `postgres` user in order to access databases from different users. http://stackoverflow.com/questions/7695962/postgresql-password-authentication-failed-for-user-postgres

**Comment by jhuseman** [comment]
When installing `psycopg2` on Ubuntu, I got an error that was corrected by first running `sudo apt-get install postgresql-server-dev-all`

**Comment by cshinaver** [comment]
Done in #35
