### ISSUE TITLE
Simulated Data Entries (Majors)

### ISSUE THREAD

**Issue by mperez14** [cshinaver/BookFinder#54]
- [x] Matt's Data
- [x] Joshua's Data
- [x] Charles's Data

**Comment by mperez14** [comment]
I Call:
Finance
Accounting
Marketing
Management/Consulting
IT_management

EE
MechE
Chemical E
Civil E
Environmental E

**Comment by mperez14** [comment]
ISBN_data.csv will be where we input all our data
Each line contains 3 items: ISBN, Name of Seller, Price for Book

The function load.py then access ISBN_data.csv and creates book objects and purchaseChoice objects based on the ISBN's that were passed in.

**Comment by jhuseman** [comment]
From Weninger's email:

'2) Recommendation engine


Get enough data to make good recommendations.


"enough" = 30 people from 5 majors total (6 per major) = 300 records = A


"good" = 300 records gets to enough data to make good recommendations.


Perform market basket analysis for recommendation.'


It looks like we might need more overlap in majors. Maybe we need to do something more like each choose two majors, and select 5 different concentrations or combinations of electives from each major. I think the overlap in this data might be important in getting good results from the market basket analysis.

**Comment by cshinaver** [comment]
> It looks like we might need more overlap in majors. Maybe we need to do something more like each choose two majors, and select 5 different concentrations or combinations of electives from each major. I think the overlap in this data might be important in getting good results from the market basket analysis.

That's a good idea. I'll do 5 from Comp sci and 5 from Math

**Comment by cshinaver** [comment]
I suggest all of us working on branch `issue_54` to add this data.

**Comment by cshinaver** [comment]
I added `ISBN_data.csv` in `bookfinder/scripts/fixtures/ISBN_data.csv`

**Comment by mperez14** [comment]
In that case I'll do EE and CHEG. Also does this mean that we are now doing 5 students for each major and across 2 different majors for a total of 10 students?

**Comment by cshinaver** [comment]
I've started work on the recommendation engine and have made significant progress. 




The data should be in the format, user_id,book_id,1 (one indicates they bought the book)

**Comment by cshinaver** [comment]
Format: `user_id,ISBN_13_num`

**Comment by jhuseman** [comment]
I'm doing MechE and CivilE

**Comment by mperez14** [comment]
Im doing EE and CPEG

**Comment by jhuseman** [comment]
I added the MechE and CivilE data just now

**Comment by cshinaver** [comment]
Matt's data is on #62

**Comment by cshinaver** [comment]
Merged in #83
