### ISSUE TITLE
Mulitple ISBN issue

### ISSUE THREAD

**Issue by mperez14** [cshinaver/BookFinder#69]
I use ISBN 10 from amazon site to add compilers book to DB
site: http://www.amazon.com/Compilers-Principles-Techniques-Tools-2nd/dp/0321486811

then in the search bar I look up: compilers aho
The first result shows the correct book but when I click on it it says there are no local copies of the book.
I think this is because the ISBN used by the search is different from the one amazon provides (i.e. maybe there are multiple isbn's for a book).
The ISBN the search bar provides is an ISBN-13 but it is different from the ISBN-13 provided by amazon, which is what leads me to believe there are (possibly) multiple ISBN's for every book.

ISBN from search:   9780321547989
ISBN from amazon: 9780321486813

**Comment by mperez14** [comment]
app

**Comment by cshinaver** [comment]
Merged in #101
